### ISSUE TITLE
Default temp dictionary location requires sudo permissions

### ISSUE THREAD

**Issue by KwanMan** [oliverwoodings/texwatch#1]
The default location for the temp dictionary requires sudo permissions for it to be created

If run without sudo it currently throws
_Potentially unhandled rejection [2] Error: EACCES, open '/usr/local/lib/node_modules/texwatch/lib/.texwatchtmpdict'_

**Comment by oliverwoodings** [comment]
Need to make the tmp file be created in the project directory, not the executing directory (i.e. don't use __dirname)
